apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  type: NodePort # Or LoadBalancer if supported by your Minikube setup
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000 # Choose an available port
